# Operationalizing Blue Carbon in the Mission-Aransas National Estuarine Research Reserve, Texas  
   
Hutchison, Lauren M.; Pollack, Jennifer B.; Swanson, Katie; Yoskowitz, David  
   
2018  
   
COASTAL MANAGEMENT  
   
### Blue carbon; carbon storage; coastal wetland; ecosystem service; mangrove  
   
   
   
Recently, greater interest in the resilience of coastal habitat ecosystem services in the northern Gulf of Mexico has emerged due in part to an expansion of mangroves into areas previously dominated by salt marshes. To operationalize coastal wetland ecosystem services for decision-making, there is a need to clarify how salt marshes and mangroves function in this region. The goal of this research is to operationalize blue carbon (carbon stored in coastal habitats) within the Mission-Aransas National Estuarine Research Reserve, TX by documenting what we know about blue carbon within the study area, identifying data gaps and future research needs, and using available knowledge to inform management and decision-making within the Reserve. Our research shows that there is a lack of data within the Reserve on mangrove aboveground biomass, belowground biomass and soil carbon and on salt marsh soil carbon. There is also a dearth of information on wetland carbon sequestration and emission rates within the Reserve, making it challenging to inform management and develop a market for blue carbon.  
   
*Research areas:  Environmental Sciences \& Ecology *
